[package]
name = "picosun2"
version = "2.0.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
image = { version = "0.25", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "dds", "qoi", "hdr", "exr", "avif", "rayon"] }
rayon = "1"
arboard = "3"

[profile.release]
opt-level = 3
lto = "thin"
