; picoSun2 installer — portable app folder -> user-local install
; Run: makensis.exe picoSun2.nsi
!define APP "picoSun2"
!define VER "2.0.0"
!define PUB "Nim4a"

Name "${APP}"
OutFile "picoSun2-setup-${VER}.exe"
Icon "icons\icon_main.ico"
UninstallIcon "icons\icon_main.ico"
InstallDir "$LOCALAPPDATA\Programs\picoSun2"
RequestExecutionLevel user
Unicode true
SetCompressor lzma
CRCCheck on
XPStyle on

!include "MUI2.nsh"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

Section "Install"
  # clean any leftover picoSun (v1) registry — it pointed at picoSun.exe via
  # run.cmd, which spawns cmd. We own picosun2.exe, so wipe the old keys first.
  DeleteRegKey HKCU "Software\picoSun"
  DeleteRegKey HKCU "Software\Classes\picoSun"
  RMDir /r "$LOCALAPPDATA\Programs\picoSun"
  SetOutPath "$INSTDIR"
  File "..\target\release\picosun2.exe"
  File "icons\icon_main.ico"
  # per-format icon pack: app icon + one doc icon per family
  File "icons\*.ico"
  WriteUninstaller "$INSTDIR\uninstall.exe"
  SetOutPath "$INSTDIR"

  # desktop + start menu shortcuts: icon comes from the exe's own resource,
  # no sidecar .ico needed (the exe embeds icon_main.ico via build.rs)
  CreateShortCut "$DESKTOP\picosun2.lnk" "$INSTDIR\picosun2.exe"
  # start menu shortcut
  CreateDirectory "$SMPROGRAMS\picosun2"
  CreateShortCut "$SMPROGRAMS\picosun2\picosun2.lnk" "$INSTDIR\picosun2.exe"
  CreateShortCut "$SMPROGRAMS\picosun2\Uninstall.lnk" "$INSTDIR\uninstall.exe"
  # registry: silent
  WriteRegStr HKCU "Software\picoSun2" "InstallDir" "$INSTDIR"
  # Applications\<exe>: what the shell uses for the "Open with" menu entry --
  # name + icon + friendly verb. Without this the entry shows no icon and a
  # bare filename.
  WriteRegStr HKCU "Software\Classes\Applications\picosun2.exe" "" "picoSun2"
  WriteRegStr HKCU "Software\Classes\Applications\picosun2.exe" "FriendlyAppName" "picoSun2"
  WriteRegStr HKCU "Software\Classes\Applications\picosun2.exe\DefaultIcon" "" "$INSTDIR\picosun2.exe,0"
  WriteRegStr HKCU "Software\Classes\Applications\picosun2.exe\shell\open\command" "" '"$INSTDIR\picosun2.exe" "%1"'
  # SupportedTypes: keep picosun2 in "Open with" for photos/RAW, never default
  WriteRegStr HKCU "Software\Classes\Applications\picosun2.exe\SupportedTypes" ".jpg" ""
  WriteRegStr HKCU "Software\Classes\Applications\picosun2.exe\SupportedTypes" ".png" ""
  WriteRegStr HKCU "Software\Classes\Applications\picosun2.exe\SupportedTypes" ".arw" ""
  # file associations (user-level, reversible): photos -> photo icon,
  # RAW -> raw icon, HDR -> hdr icon, animations -> anim icon. picoSun2 is
  # registered as OpenWith for everything, default for nothing -- the user
  # picks it in "Open with", we never hijack their defaults.
  WriteRegStr HKCU "Software\Classes\picoSun2.photo\DefaultIcon" "" "$INSTDIR\icon_photo.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun2.photo\shell\open\command" "" '"$INSTDIR\picosun2.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\picoSun2.raw\DefaultIcon" "" "$INSTDIR\icon_raw.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun2.raw\shell\open\command" "" '"$INSTDIR\picosun2.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\picoSun2.hdr\DefaultIcon" "" "$INSTDIR\icon_hdr.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun2.hdr\shell\open\command" "" '"$INSTDIR\picosun2.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\picoSun2.anim\DefaultIcon" "" "$INSTDIR\icon_anim.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun2.anim\shell\open\command" "" '"$INSTDIR\picosun2.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\.avif\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.bmp\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.cur\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.cut\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.dds\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.dib\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.emf\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.exif\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.fax\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.flif\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.hdp\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.heic\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.heif\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.hif\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.ico\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.j2k\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.jfif\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.jp2\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.jpe\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.jpeg\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.jpg\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.jxl\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.jxr\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.mjpeg\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.pbm\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.pcx\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.pgm\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.png\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.pnm\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.ppm\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.psb\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.psd\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.qoi\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.svg\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.svgz\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.tga\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.tif\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.tiff\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.viff\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.wbm\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.wdp\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.wmf\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.wpg\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.xbm\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.xpm\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.xv\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\Classes\.3fr\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.ari\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.arq\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.arw\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.bay\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.cap\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.cr2\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.cr3\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.crw\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.dcr\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.dcs\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.dng\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.drf\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.eip\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.erf\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.fff\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.gpr\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.iiq\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.k25\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.kdc\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.mdc\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.mef\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.mos\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.mrw\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.nef\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.nrw\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.obm\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.orf\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.pef\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.ptx\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.pxn\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.r3d\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.raf\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.raw\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.rw2\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.rwl\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.rwz\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.sr2\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.srf\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.srw\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.x3f\OpenWithProgids" "picoSun2.raw" ""
  WriteRegStr HKCU "Software\Classes\.exr\OpenWithProgids" "picoSun2.hdr" ""
  WriteRegStr HKCU "Software\Classes\.fits\OpenWithProgids" "picoSun2.hdr" ""
  WriteRegStr HKCU "Software\Classes\.hdr\OpenWithProgids" "picoSun2.hdr" ""
  WriteRegStr HKCU "Software\Classes\.pfm\OpenWithProgids" "picoSun2.hdr" ""
  WriteRegStr HKCU "Software\Classes\.ani\OpenWithProgids" "picoSun2.anim" ""
  WriteRegStr HKCU "Software\Classes\.apng\OpenWithProgids" "picoSun2.anim" ""
  WriteRegStr HKCU "Software\Classes\.gif\OpenWithProgids" "picoSun2.anim" ""
  WriteRegStr HKCU "Software\Classes\.gifv\OpenWithProgids" "picoSun2.anim" ""
  WriteRegStr HKCU "Software\Classes\.webp\OpenWithProgids" "picoSun2.anim" ""
  WriteRegStr HKCU "Software\Classes\3gp\OpenWithProgids" "picoSun2.photo" ""
  WriteRegStr HKCU "Software\picoSun2" "AssocVer" "1"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun2" "DisplayName" "picoSun2 ${VER}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun2" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun2" "Publisher" "${PUB}"
SectionEnd

Section "Uninstall"
  RMDir /r "$INSTDIR"
  Delete "$DESKTOP\picoSun2.lnk"
  RMDir /r "$SMPROGRAMS\picoSun2"
  DeleteRegKey HKCU "Software\picoSun2"
  DeleteRegValue HKCU "Software\Classes\.avif\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.bmp\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.cur\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.cut\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.dds\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.dib\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.emf\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.exif\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.fax\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.flif\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.hdp\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.heic\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.heif\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.hif\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.ico\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.j2k\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.jfif\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.jp2\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.jpe\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.jpeg\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.jpg\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.jxl\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.jxr\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.mjpeg\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.pbm\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.pcx\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.pgm\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.png\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.pnm\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.ppm\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.psb\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.psd\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.qoi\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.svg\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.svgz\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.tga\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.tif\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.tiff\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.viff\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.wbm\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.wdp\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.wmf\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.wpg\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.xbm\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.xpm\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.xv\OpenWithProgids" "picoSun2.photo"
  DeleteRegValue HKCU "Software\Classes\.3fr\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.ari\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.arq\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.arw\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.bay\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.cap\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.cr2\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.cr3\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.crw\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.dcr\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.dcs\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.dng\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.drf\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.eip\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.erf\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.fff\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.gpr\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.iiq\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.k25\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.kdc\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.mdc\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.mef\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.mos\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.mrw\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.nef\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.nrw\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.obm\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.orf\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.pef\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.ptx\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.pxn\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.r3d\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.raf\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.raw\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.rw2\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.rwl\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.rwz\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.sr2\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.srf\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.srw\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.x3f\OpenWithProgids" "picoSun2.raw"
  DeleteRegValue HKCU "Software\Classes\.exr\OpenWithProgids" "picoSun2.hdr"
  DeleteRegValue HKCU "Software\Classes\.fits\OpenWithProgids" "picoSun2.hdr"
  DeleteRegValue HKCU "Software\Classes\.hdr\OpenWithProgids" "picoSun2.hdr"
  DeleteRegValue HKCU "Software\Classes\.pfm\OpenWithProgids" "picoSun2.hdr"
  DeleteRegValue HKCU "Software\Classes\.ani\OpenWithProgids" "picoSun2.anim"
  DeleteRegValue HKCU "Software\Classes\.apng\OpenWithProgids" "picoSun2.anim"
  DeleteRegValue HKCU "Software\Classes\.gif\OpenWithProgids" "picoSun2.anim"
  DeleteRegValue HKCU "Software\Classes\.gifv\OpenWithProgids" "picoSun2.anim"
  DeleteRegValue HKCU "Software\Classes\.webp\OpenWithProgids" "picoSun2.anim"
  DeleteRegValue HKCU "Software\Classes\3gp\OpenWithProgids" "picoSun2.photo"
  DeleteRegKey HKCU "Software\Classes\Applications\picosun2.exe"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun2"
SectionEnd